
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Sep 16 01:54:16 CEST 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 11;
  public static final int CONST = 5;
  public static final int ASSIGNMENT = 25;
  public static final int NOT_EQUAL = 43;
  public static final int GREATER = 38;
  public static final int CONTINUE = 36;
  public static final int LPAREN = 30;
  public static final int NUM_CONST = 10;
  public static final int FOR = 34;
  public static final int MINUS = 15;
  public static final int RPAREN = 31;
  public static final int SEMICOLON = 28;
  public static final int AND = 12;
  public static final int OR = 13;
  public static final int QMARK = 19;
  public static final int COMMA = 29;
  public static final int INC = 26;
  public static final int DIV = 17;
  public static final int LESSER = 40;
  public static final int PLUS = 14;
  public static final int IF = 32;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int EQUAL = 39;
  public static final int GREATER_EQUAL = 41;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 16;
  public static final int MOD = 18;
  public static final int BREAK = 35;
  public static final int IDENT = 9;
  public static final int VOID = 6;
  public static final int COLON = 20;
  public static final int LBRACE = 21;
  public static final int ELSE = 33;
  public static final int LSQUARE = 23;
  public static final int READ = 4;
  public static final int RSQUARE = 24;
  public static final int RBRACE = 22;
  public static final int LESSER_EQUAL = 42;
  public static final int BOOL_CONST = 8;
  public static final int DEC = 27;
  public static final int PRINT = 3;
}

